### ISSUE TITLE
"true" in Json ignored

### ISSUE THREAD

**Issue by jkblgithub** [3lvis/Sync#399]
My json includes "true" or "false" for bool fields. However, values with true are set as false in Core Data when calling` [Sync changes: inEntityName ...]` Is there a workaround for this please?

**Comment by jkblgithub** [comment]
Has this library now been abandoned?

**Comment by 3lvis** [comment]
Hi @jkblgithub,

Sorry for not being more responsive, just not a lot of time to look into issues these days between a new job and learning Norwegian, pretty much out of my home from 8 am to 10 pm.

Forking the project and adding a failing unit test will help a lot to get this issue resolved since it's usually the part that takes most time when fixing issues.

**Comment by 3lvis** [comment]
Hi @jkblgithub,

Any chance to get a failing test or a project that reproduces this?

**Comment by 3lvis** [comment]
Haven't seen any other issues related to this so might be an isolated case and not something related to the library, closing unless anything changes.
