### ISSUE TITLE
no documentation? I can't figure out how to use this 

### ISSUE THREAD

**Issue by siempay** [3lvis/Sync#454]
I have a `model.xcodedatamodeld` in a framework integrated in my app 
and I want to sync objects to my model!
how can I do that ?
what is dataStack ? you do not use it in your example !

what I understood is something like this 
`DataStack(name:"Model").sync(usersJson, inEntityNamed: Users.entity().name!, completion: { (e) in				})`
but it can not find the Model 
`2017-11-22 21:13:47.527082+0000 app3[2312:1375074] [error] error:  Failed to load model named Model`

note that my model dose not exist in  my app, but it exist in a framework (model) where I have all my entities and I do a `import model` in my app

**Comment by 3lvis** [comment]
Hi Brahim,

If your Core Data model is located inside your framework you need to do this.

```swift
let frameworkBundle = Bundle(identifier: "com.framework.identifier")!
self.dataStack = DataStack(modelName: "NameOfTheModel", bundle: frameworkBundle, storeType: .sqLite)
```

**Comment by 3lvis** [comment]
I updated the iOSDemo to use DataStack instead of persistency container: https://github.com/3lvis/Sync/blob/master/iOSDemo/Library/Fetchers/Fetcher.swift

**Comment by siempay** [comment]
do I have to use dataStack? and if I do! will I have to use it for all communication with my model?
like adding, updating, deleting and fetching from my model will go through it ?

**Comment by siempay** [comment]
when I do fetch with mainContext or viewContext even if I don't know the difference between theme, I get a list of `[User]` with length of 2 as I inserted (my json from server has two users in it) but when I try to access to any property (i.e id or name) i get nil even

**Comment by 3lvis** [comment]
>do I have to use dataStack? and if I do! will I have to use it for all communication with my model?
like adding, updating, deleting and fetching from my model will go through it ?

You don't have to but is better if you do, DataStack is an abstraction over Core Data's boilerplate.

**Comment by 3lvis** [comment]
>mainContext and viewContext are the same, it's just a convenience name.

**Comment by 3lvis** [comment]
>I get a list of [User] with length of 2 as I inserted (my json from server has two users in it) but when I try to access to any property (i.e id or name) i get nil even

Could you share a sample of your implementation so I can check the issues?

**Comment by siempay** [comment]
about this last one, sorry it was my bad, It was that attributes names did not match the ones in from the server. so I get nil in some but I get a value in others who were matched

**Comment by 3lvis** [comment]
That's correct they should be either snake_case or the same as your Core Data model.

Example:
Core Data field: userID
JSON: user_id or userID

**Comment by 3lvis** [comment]
Let me know if this was resolved so we can close this issue, otherwise I'm happy to help :)

**Comment by siempay** [comment]
just one thing, so if i have in my model file an attribute called **`someAttributeName`**, 
it is gonna be mapped with both of these  

- `{ "someAttributeName" : "some value"}` 

- `{ "some_attribute_name" : "some value"}`

**Comment by 3lvis** [comment]
That's correct but there are two exceptions: reserved attributes and acronyms.

I'm pasting the section about attribute mapping from the README here.

### Attribute Mapping

Your attributes should match their JSON counterparts in `camelCase` notation instead of `snake_case`. For example `first_name` in the JSON maps to `firstName` in Core Data and `address` in the JSON maps to `address` in Core Data.

There are some exception to this rule:

* Reserved attributes should be prefixed with the `entityName` (`type` becomes `userType`, `description` becomes `userDescription` and so on). In the JSON they don't need to change, you can keep `type` and `description` for example. A full list of reserved attributes can be found [here](https://github.com/3lvis/Sync/blob/master/Source/PropertyMapper/NSManagedObject%2BPropertyMapperHelpers.m#L282-L284)
* Attributes with acronyms will be normalized (`id`, `pdf`, `url`, `png`, `jpg`, `uri`, `json`, `xml`). For example `user_id` will be mapped to `userID` and so on. You can find the entire list of supported acronyms [here](https://github.com/3lvis/Sync/blob/master/Source/Inflections/Inflections.m#L204-L206).

If you want to map your Core Data attribute with a JSON attribute that has different naming, you can do by adding `sync.remoteKey` in the user info box with the value you want to map.

**Comment by zhihuilong** [comment]
I just want to map firstName(JSON) to firstName(Core Data). Is there any solutions to achieve this? @3lvis

**Comment by zhihuilong** [comment]
It's really annoying that you cannot map two value which has the same name.

**Comment by 3lvis** [comment]
@zhihuilong firstName to firstName should just work.

**Comment by 3lvis** [comment]
I need to update the documentation to point this out but now we support snake_case and camelCase in the JSON.
