### ISSUE TITLE
crash when syncing large amounts of data; managedObjectContext == nil, workaround

### ISSUE THREAD

**Issue by frankkienl** [3lvis/Sync#465]
When the app is syncing large amounts of data, and the user requests a sync that will replace/update/delete data that is being synced, the app crashes.

I traced the crash back to:
`guard let managedObjectContext = managedObjectContext else { abort() }`
https://github.com/3lvis/Sync/blob/master/Source/Sync/NSManagedObject%2BSync.swift#L226

Sometimes, the managedObjectContext is nil, therefore crashing the app.

I've made a workaround, instead of using managedObjectContext, use context, which is a parameter given when the function `func sync_toManyRelationship` is called.
https://github.com/3lvis/Sync/blob/master/Source/Sync/NSManagedObject%2BSync.swift#L196

So in `func sync_toManyRelationship` I replaced `managedObjectContext` with `context`.
This seems to work. No more crashes. But i'm not sure this is the correct solution for this problem.

See:
Original:
https://github.com/3lvis/Sync/blob/master/Source/Sync/NSManagedObject%2BSync.swift#L257
Changed:
https://github.com/frankkienl/Sync/blob/master/Source/Sync/NSManagedObject%2BSync.swift#L259

**Comment by 3lvis** [comment]
Hi Frank,

Thanks for this fix, I believe what you share is correct, doesn't really make much sense to use the managedObjectContext when provided by a parameter. The reason was that the context as a parameter was introduced later to fix a different issue and pass it down to one of the methods called inside this method, since at the moment I didn't find any use cases that required the change I didn't do it.

Now, I agree that your change makes more sense and I see that all the tests work fine but I would like to reproduce the crash to make sure we don't break it again in the future. Is there any chance you could help me reproduce the issue with a unit test?

**Comment by frankkienl** [comment]
I'll see what I can do.

It was hard to reproduce with the real app,  it happend only sometimes and only when using the real database. So it might not be easy to make it happen in a unit test.

If I'm able to create a minimal app, with minimal testdata that can still reproduce the error, I'll share it ;-)
