### ISSUE TITLE
Deletion of ManagedObjects leads to deletion of its inheritance objects

### ISSUE THREAD

**Issue by Drenov** [3lvis/Sync#484]
There are two ManagedObjects:
- Foo: NSManagedObjects         
- Bar: Foo          

This code, used for deletion, works normally, only objects of Foo removed:

```
 Sync.changes([[String: Any]](), inEntityNamed: "Bar", dataStack: dataManager.dataStack, operations: [.delete]) { error in
                handleError(error)
            }

```
But when try to delete Foo objects via:

```
 Sync.changes([[String: Any]](), inEntityNamed: "Foo", dataStack: dataManager.dataStack, operations: [.delete]) { error in
                handleError(error)
            }
```
The SQL table becomes empty. There are no Foo, nor Bar.

Is such behaviour expected?

**Comment by 3lvis** [comment]
Hi @Drenov, I think this is because of the way you've setup the Core Data Delete Rules, could you verify if changing the Delete Rule to "Nullify" helps?

![figure-core-data-relationships-delete-rules-1](https://user-images.githubusercontent.com/1088217/36585473-4ca8ae18-187e-11e8-9d08-fb200d3ec27f.jpg)

More info on deletion rules here: https://cocoacasts.com/core-data-relationships-and-delete-rules

**Comment by Drenov** [comment]
Hello @3lvis, I've found reasons for that. It is normal native Core Data behaviour for inherited objects. So the decision is to use base class as abstract.

**Comment by 3lvis** [comment]
I'm glad you were able to fix this issue @Drenov, let me know if I can help in anything else :)
