### ISSUE TITLE
Crash on inMemory sync

### ISSUE THREAD

**Issue by joshxplor** [3lvis/Sync#491]
I keep getting this crash 
> "The left hand side for an ALL or ANY operator must be either an NSArray or an NSSet."

works well with sqlite persistent store. 

     [{  
          "sampleId":1,
          "somePropertyArray":[{  
                                 "arrayId":2,
                                 "anotherArrayProperty":[{  
                                                           "anotherArrayId":3
                                                         }]
                              }]
        }]

**Comment by 3lvis** [comment]
Hi @joshxplor,

Can you help us reproducing the issue by adding a unit test or sharing your Core Data model?

**Comment by joshxplor** [comment]
@3lvis 

Will provide a unit test. I did fork this project and run the test, but seems that the NSManagedObject+Sync is different with the current version? 

on line 327 of the fork it was using `childPredicate = NSPredicate(format: "%K IN %@ OR %K = %@", entity.sync_localPrimaryKey(), ids, inverseEntityName, self)` in the current version though it uses this `childPredicate = NSPredicate(format: "ANY %K IN %@ OR %K = %@", entity.sync_localPrimaryKey(), ids, inverseEntityName, self)`

so I tried to use the current predicate with `ANY` and run the test in memory. almost half of the test cases are failing.

**Comment by rebe1one** [comment]
I am also running into some issues with these new changes when running this in an in-memory store. I'm having a little trouble understanding the need for the ANY operator here. Since the first parameter in the predicate is the local primary key I can only imagine ANY working if it was actually an array, but the general use case is probably not going to be. Is there something I'm misunderstanding here?

**Comment by joeboyscout04** [comment]
I've gotten this same error under similar conditions...I think it may have something to do with the data being on different threads.

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
