### ISSUE TITLE
SYNC support Codeable, Decodeable? 

### ISSUE THREAD

**Issue by petkrein** [3lvis/Sync#505]
Hey Elvis,

will sync someday support Codeable, Decodeable?

[https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types)

**Comment by 3lvis** [comment]
Hi @petkrein!

What's a good question, I haven't got around thinking how it could work. Right now Core Data makes it very easy since I can inspect the objects and attributes using the Core Data model. In order to make it work with Decodable I would have to generate somehow a relationship model to be able to do the Sync. If you have any ideas on how to do this I would be happy to collaborate on it. :)

**Comment by 3lvis** [comment]
Closing since this isn't part of the roadmap at the moment, but thanks for your feedback @petkrein! Happy to help in anything else.
