### ISSUE TITLE
Issue in Syncing Large Data 

### ISSUE THREAD

**Issue by himu243** [3lvis/Sync#515]
Im fetching large response  data from service call. Service is sending response in pages and in one page, there is 5000 records. I ve applied the logic in such a way that while device is fetching data from page 2, data of page 1 is getting saved using **dataStack.sync** . But, when i see the database, data of page 1 is missing and is saved only pages 2 and 3. 
![screen shot 2018-07-19 at 11 38 00 pm](https://user-images.githubusercontent.com/25073381/42961670-08225508-8bad-11e8-89a0-568c4205d7c1.png)
![screen shot 2018-07-19 at 11 38 48 pm](https://user-images.githubusercontent.com/25073381/42961672-0856f1e6-8bad-11e8-8f6e-9a03869aa5ab.png)
![screen shot 2018-07-19 at 11 39 21 pm](https://user-images.githubusercontent.com/25073381/42961673-0883a9b6-8bad-11e8-8a3f-62cbadb5cb4b.png)
Here are the snippets on one of my service call.. Can u see to it and lemme know what am i doing wrong ?

**Comment by 3lvis** [comment]
Hi @himu243! To get some inside in how Sync works you can refer to the following guide: https://github.com/3lvis/Sync/blob/master/docs/how-it-works.md

Basically, what is happening is that Sync compares your JSON against your Core Data items, then it makes a diff and deletes, inserts and updates the relevant items. In your case the new JSON is comparing your items from the first page, since they are different it replaces them. 

One way to fix this is to use a predicate with Sync, when you call the method you can say: "Only compare the JSON with items with id: 1, 2, 3, 4, 5 and so on".

In order to do this before calling Sync you can make a query to get all the IDs then in your Sync predicate you can say: "id in %@, array" for example. I hope this makes sense otherwise let me know and I'll try to expand.

Have a nice day!

**Comment by 3lvis** [comment]
Closing for lack of feedback.
