### ISSUE TITLE
Where did my sql files go?

### ISSUE THREAD

**Issue by jimijon** [3lvis/Sync#521]
self.dataStack = DataStack(modelName: "GF-Model", bundle: Bundle.main, storeType: .sqLite, storeName: "NFDB-6.0")
            
I used to see them in my Document directory but now they are gone.

NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).last! as String

4.1.3 --> 4.2 broke this

**Comment by 3lvis** [comment]
@jimijon damn, I think I found the issue v

**Comment by 3lvis** [comment]
Hi James, I've made a new release please let me know if this fixes your issue.

https://github.com/3lvis/Sync/releases/tag/4.2.1

Also in order to make the tests run in the CI I had to switch between caches folder and documents folder so might be better if you could use 	`FileManager.sqliteDirectoryURL`.

Fix for CircleCI here: https://github.com/3lvis/Sync/pull/518/files

**Comment by jimijon** [comment]
It’s back! Thanks for the prompt fix.
