### ISSUE TITLE
Performance issue when syncing

### ISSUE THREAD

**Issue by dneykov** [3lvis/Sync#531]
Hi,

I'm using Sync for dropdowns in a form. I have about 15 fields and the relations are the options about 12k-15k. When sync process starts memory jumps to 500-600MB and takes few minutes. I'm wondering if this is Core Data problem or I can do something to speed it up. 
Response that I get is not that big is about 900KB and response time is 1.5-2 seconds but Syncing is very slow.
I'm using Sync in `newNonMergingBackgroundContext`. 

Thanks.

**Comment by 3lvis** [comment]
Hi @dneykov,

When performance is an issue, I would advise you to try a solution closer to your problem instead of Sync, sadly Sync trades convenience for performance, I have tried to make it more performant but I think I have reached the point where more performance will come at the cost of maintenance.

**Comment by dneykov** [comment]
Hi @3lvis,

Thanks for your quick reply. Sync is great library. Can you give me any advise how can I achieve that? Will be better if I iterate over my response and insert everything manually?

**Comment by 3lvis** [comment]
Closing for now, I wish I could be more helfpul.
