### ISSUE TITLE
Application crash on Model.export() 

### ISSUE THREAD

**Issue by siempay** [3lvis/Sync#535]
this is a screen of xcode organizer:

![capture d ecran 2018-09-16 a 18 48 00](https://user-images.githubusercontent.com/14646888/45599366-49667900-b9e2-11e8-8462-d0fb76892904.png)

what do thing could be the reason of this crash! 
it happened multiple times but not all times

**Comment by 3lvis** [comment]
Hi @siempay,

Might be a strange key or a recursive export call. Can you share an image of your core data model?

**Comment by siempay** [comment]
I doubt it is a recursive export because I checked multiple times, and I know when it is a recursive export. So what is this "strange key" ?
The model is a bit big I dont know how it is gonna help ?

**Comment by 3lvis** [comment]
Hi @siempay!

I can't think of a scenario that would be causing this from the top of my head. Any pointers on what can I do to reproduce the issue?

**Comment by siempay** [comment]
Hi @3lvis :
This crash just happened on my watch!
Selecting the last line where it stopped in the threads , 
I did a `(lldb) po self` and this was the result :
`<FamilleGmmPrdCnsPrcpl: 0x1c828b400> (entity: FamilleGmmPrdCnsPrcpl; id: 0xd000000000200036 <x-coredata://54329177-386C-4868-86EB-E1390BC80F33/FamilleGmmPrdCnsPrcpl/p8> ; data: <fault>)`

Even though when I go back one line to see the parent of this relationship.
I do `(lldb) po self`, it prints an object correctly 
I dont know what this `<fault>` ! is it the problem ?
What should I do to fixe this?
Thank you.

**Comment by 3lvis** [comment]
Hi @siempay!

<fault> is what Core Data uses instead of the full object, it's used for optimization purposes, you can read more about faults here: https://cocoacasts.com/reading-and-updating-managed-objects-with-core-data

When using `po` you need to do `po self.willAccessValue(forKey: nil)` so it converts from <fault> to data, then we will be able to find the issue. I think the best is for us to figure out first if this isn't a data issue and would be nice to get a `po` of the full object if you could do that.

I believe the error has to do with either Core Data trying to access a deleted relationship, so in your JSON in one entry the relationship is deleted and in other entry the relationship is trying to be read. This can be solved by changing your relationships from "one-to-many" to "many-to-many" a lot of times when we are building our models we would make assumptions that are different in the backend and that could cause this issue. Changing from "one-to-many" to "many-to-many" (or the other way) changes the policy for deleting relationships.

My other theory is that there's some data corruption happening that is causing Core Data to fail, we'll only resolve this by seeing the full object. 

I hope this helps even a bit, this things are a bit hard to explain on written so if anything is not clear please let me know and I'll try to explain a bit more.

**Comment by siempay** [comment]
Hi @3lvis ,
Thanks for the replay, for the `po self.willAccessValue(forKey: nil)` , I got this: 
`error: property 'willAccessValue' not found on object of type 'NSManagedObject *'
error: use of undeclared identifier 'forKey'`

**Comment by siempay** [comment]
Hi @3lvis ,
Thanks for the replay, for the `po self.willAccessValue(forKey: nil)` , I got this: 
`error: property 'willAccessValue' not found on object of type 'NSManagedObject *'
error: use of undeclared identifier 'forKey'`

**Comment by 3lvis** [comment]
I haven't had a similar report and it's very strange that sometimes happens and sometimes not. Sorry for not being more helpful but without being able to reproduce it it's very little I can do besides speculating on what could be the issue.

**Comment by 3lvis** [comment]
Hi! Yes, had a look and it could be a problem. It's better if you run export on an object retreieved from the main context.

**Comment by KaiqueDamato** [comment]
Hi @3lvis,

I think I'm facing a similar issue. I'm doing a new version of my app and on the new version I will send the data to the cloud. When I update my app with some core data objects to the new version and try to export it, it crashes. But sometimes all works fine.

If I create a new object on the new version and try to export it everything works as expected. 

I've checked the objects and all it seems fine. 

When the exports fails this is the crash that occurs:

<img width="1680" alt="screen shot 2018-10-24 at 17 28 12" src="https://user-images.githubusercontent.com/10827761/47459335-42d1db00-d7b2-11e8-959a-b2e9388c9a9c.png">

Do you have any thoughts on that?

Thank you in advance.

**Comment by 3lvis** [comment]
Hi @KaiqueDamato, 

Is there any chance you could help me to isolate the issue? Maybe with a JSON file and a Core Data model?

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
