### ISSUE TITLE
Cancel sync process

### ISSUE THREAD

**Issue by zoltanbognar** [3lvis/Sync#540]
Hi Guys

Is there a way to cancel a syncing process? I haven't found it in the documentation.
I'm syncing a downloaded json to core data with DataStack. it can take a while, when json has lets say 50 entities. 
e.g when user logs out from the app I'm deleting his data from database, but when he logs out during sync and the sync is finished after he logged out, then the deleted data is unfortunatly back in the database. 
So anyway I want to cancel syncing when user logs out.

Thanks for help

Zoltan

**Comment by 3lvis** [comment]
Hi! Sync uses (NS)Operations, so if you make an OperationQueue and add sync to it then you can cancel it at any point.

**Comment by 3lvis** [comment]
I'll see if I can add some docs later, but here are you see Sync is a subclass of Operation: https://github.com/3lvis/Sync/blob/b51324ec8368066624c603c98e63cb417b2bccf5/Source/Sync/Sync.swift#L17

**Comment by 3lvis** [comment]
Hi Zoltan,

You're right, error handling wasn't 100% finished, I'm using `try` and `throws` as much as possible but for the cases where this can't be used (closures and overriding methods) I haven't been able to find the time to complete error handling.

I think we might need to introduce a `delegate` to the operation in order to inform what failed, or do you have another suggestion in how to inform about an error from inside an operation. :)

Best

**Comment by zoltanbognar** [comment]
Hi Elvis

one approach can be to add public error variable to Sync class:
public var error: NSError?

and than: 
func perform(using context: NSManagedObjectContext) {
        do {
            try Sync.changes(self.changes, inEntityNamed: self.entityName, predicate: self.predicate, parent: self.parent, parentRelationship: self.parentRelationship, inContext: context, operations: self.filterOperations, shouldContinueBlock: { () -> Bool in
                return !self.isCancelled
            }, objectJSONBlock: { objectJSON -> [String: Any] in
                return self.delegate?.sync(self, willInsert: objectJSON, in: self.entityName, parent: self.parent) ?? objectJSON
            })
        } catch let error as NSError {
            print("Failed syncing changes \(error)")
            self.error = error
        }

        self.updateExecuting(false)
        self.updateFinished(true)
    }

in the code user can check for e.g. error like this:
let sync = Sync(changes: changes, inEntityNamed: entityName, dataStack: dataStack, operations: syncOptions)
        sync.completionBlock = { [unowned sync] in
            if let completion = completion {
                completion(sync.error)
            }
        }

but maybe there is better aproach

Best 

Zoltan

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
