### ISSUE TITLE
How to change date format of exported objects?

### ISSUE THREAD

**Issue by siempay** [3lvis/Sync#543]
the format of exported date is maybe this `"yyyy-MM-dd'T'HH:mm:ssZZZZZ` .
but I want to change it to `yyyy-MM-dd HH:mm:ss` for all exports.
is there a global way to do that

**Comment by 3lvis** [comment]
Hi @siempay! 

In the `export` method you can use the `ExportOptions` which has a `dateFormatter` inside.

`public func export(using options: ExportOptions) -> [String: Any]`

You can provide your own dateFormatter to get the format that you want.

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
