### ISSUE TITLE
fatal error when trying to save json

### ISSUE THREAD

**Issue by ltAldoRaine** [3lvis/Sync#551]
I have just started using sync library, it's very comfortable and thanks you all for contributing.

I have this scenario:

Api returns **JSON** like this:

[https://i.imgur.com/akk3WwW.png](https://i.imgur.com/akk3WwW.png)

My Core Data model looks like this:

(userId is primary key)

[https://imgur.com/ERqiy5r](https://imgur.com/ERqiy5r)

fatal error occures when syncing data

[https://imgur.com/uXdGovt](https://imgur.com/uXdGovt)

[https://imgur.com/GGRCji6](https://imgur.com/GGRCji6)

Am i doing something wrong?

**Comment by 3lvis** [comment]
Hi @ltAldoRaine 

Why is everything Binary Data? That doesn't seem right. 

You might want to try doing something like

`userID.value: String`
`nickname.value: String`

And so on

**Comment by ltAldoRaine** [comment]
Thanks @3lvis !

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
