### ISSUE TITLE
In search of existing solution for how to output id instead of whole object in relationships

### ISSUE THREAD

**Issue by robert-dodier** [3lvis/Sync#562]
Hi, I'd like to output relationships as just the id instead of the whole object. I believe that this issue: https://github.com/3lvis/Sync/issues/415 is just the same. At that time (August 2017) there wasn't a way to output the referred-to id instead of the whole object -- has the situation changed since #415 was posted?

The best solution I have come to is to modify the [String: Any] dictionary which is returned by `export`. I am thinking I can look for the keys which correspond to referred-to objects, and replace the value with just the id of the referred-to object. Is there any reason to think that's not a good idea? Has anyone already implemented that? Has anyone already implemented a different solution?

By the way, I am assuming that Sync doesn't have a built-in way to export relationships by id -- have I overlooked something? If there's a built-in way to handle it, that would be ideal.

Thank you in advance for any information on this topic.

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
