### ISSUE TITLE
Date sync with iOS 13.2 doesn't store in the data model

### ISSUE THREAD

**Issue by revdbrink** [3lvis/Sync#570]
I use the current latest version 6.0.0 if I save an object with datastack.sync with date values in it to the core data model it works perfect with iOS 12. But the same code on an iOS 13.2 device he doesn't store the date in the database. The value is empty.
An example date which I use is "date" -> "2019-11-21T09:25:38+01:00"

**Comment by 3lvis** [comment]
Hi @revdbrink,

Thanks for reporting this, I'll see if I can reproduce it.

**Comment by revdbrink** [comment]
@3lvis any news? Can you also reproduce this?

**Comment by revdbrink** [comment]
@3lvis will there be a fix for this?

**Comment by revdbrink** [comment]
Any news if you can reproduce this and there will be a fix?

**Comment by 3lvis** [comment]
Thanks for your support in this library. It has been a while since I used CoreData in any of my projects and it's hard for me to maintain this library. If you have been part of the Sync contributors group and want to take ownership of the library let me know to elvisnunez@me.com. For now, I'll be archiving this library.
